"""
Centralizuota konfigūracija
"""

# PROFIT MODE
PROFIT_MODE_ENABLED = True
PROFIT_DAILY_TARGET_EUR = 15.0
PROFIT_MAX_TRADES_PER_DAY = 6
PROFIT_POSITION_MULTIPLIER = 1.3

# BEAR MARKET
BEAR_MARKET = {
    "FORCE_ACTIVATE": False,
    "STRENGTH": 85.0,
    "OVERRIDE_AUTO_DETECT": False,
    "MANUAL_OVERRIDE_LOCK": False
}

# RISK MANAGEMENT
RISK = {
    "CRITICAL_ALERT_COOLDOWN": 3600,
    "DAILY_LOSS_LIMIT_PCT": 1.5,
    "WEEKLY_LOSS_LIMIT_PCT": 5.0,
    "MAX_POSITIONS": 5
}

# TRADING HOURS
TRADING_HOURS_ENABLED = False  # Išjungta testavimui

# ZONE RESOLUTION
ZONE_RESOLUTION_MIN_BODY_PCT = 0.6
ZONE_RESOLUTION_REQUIRED_CLOSES = 2
